# 2.7 array的分割

In [1]:
import numpy as np

In [2]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
print(np.vsplit(A, 3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [6]:
print(np.hsplit(A, 2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


# 2.8 copy&deep copy

In [7]:
a = np.arange(4)

In [8]:
b = a 
c = a
d = b

In [9]:
a[0] = 11

In [11]:
print(a)

[11  1  2  3]


In [13]:
b is a

True

In [14]:
d is a

True

In [15]:
b = a.copy()

In [16]:
print(b)

[11  1  2  3]


In [17]:
a[3]=44

In [18]:
print(a)

[11  1  2 44]


In [19]:
print(b)

[11  1  2  3]


# 3.1 pandas基本介绍

In [20]:
import pandas as pd

In [21]:
s = pd.Series([1,3,6,np.nan,44,1])

In [22]:
print(s)

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64


In [23]:
dates = pd.date_range('20180913',periods=6)

In [24]:
print(dates)

DatetimeIndex(['2018-09-13', '2018-09-14', '2018-09-15', '2018-09-16',
               '2018-09-17', '2018-09-18'],
              dtype='datetime64[ns]', freq='D')


In [26]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=['a','b','c','d'])

In [27]:
print(df)

                   a         b         c         d
2018-09-13  0.292695  0.624411 -0.376373 -0.389735
2018-09-14  0.622851 -0.693294  0.387914 -0.183085
2018-09-15  0.304645  1.344926  1.452809  1.253915
2018-09-16 -0.949070 -0.392246  0.404040  0.294650
2018-09-17  0.489718  2.829349 -0.670353  1.226522
2018-09-18  1.257559  1.405304  0.477352 -1.282753


In [31]:
print(np.random.random((3,4)))

[[0.99545954 0.0957518  0.86788692 0.32207226]
 [0.59198293 0.49399267 0.60103713 0.22542934]
 [0.08674966 0.77771919 0.80882665 0.20389411]]


In [34]:
df1 = pd.DataFrame(np.arange(12).reshape((3,4)))
print(df1)

   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11


In [35]:
df2 = pd.DataFrame({'A':1.,
                   'B':pd.Timestamp('20180913'),
                   'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                   'D':np.array([3]*4,dtype='int32'),
                   'E':pd.Categorical(["test","train","test","train"]),
                   'F':'foo'})
print(df2)

     A          B    C  D      E    F
0  1.0 2018-09-13  1.0  3   test  foo
1  1.0 2018-09-13  1.0  3  train  foo
2  1.0 2018-09-13  1.0  3   test  foo
3  1.0 2018-09-13  1.0  3  train  foo


In [37]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [39]:
df2.index

Int64Index([0, 1, 2, 3], dtype='int64')

In [40]:
df2.columns

Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='object')

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [44]:
df2.values

array([[1.0, Timestamp('2018-09-13 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2018-09-13 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2018-09-13 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2018-09-13 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [45]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

In [46]:
df2.T

0                    1                    2  \
A                    1                    1                    1   
B  2018-09-13 00:00:00  2018-09-13 00:00:00  2018-09-13 00:00:00   
C                    1                    1                    1   
D                    3                    3                    3   
E                 test                train                 test   
F                  foo                  foo                  foo   

                     3  
A                    1  
B  2018-09-13 00:00:00  
C                    1  
D                    3  
E                train  
F                  foo

# 3.2 pandas选择数据

In [49]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.arange(24).reshape((6,4)),index=dates,columns=['A','B','C','D'])
df

A   B   C   D
2013-01-01   0   1   2   3
2013-01-02   4   5   6   7
2013-01-03   8   9  10  11
2013-01-04  12  13  14  15
2013-01-05  16  17  18  19
2013-01-06  20  21  22  23

In [50]:
df['A']

2013-01-01     0
2013-01-02     4
2013-01-03     8
2013-01-04    12
2013-01-05    16
2013-01-06    20
Freq: D, Name: A, dtype: int32